# 개발 환경 설정
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/zonie-chat-dev
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: INFO
    com.grm3355.zonie: DEBUG
